[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "CDLA-Permissive-2.0"]
exceptions = [{ allow = ["LGPL-2.1"], crate = "libudev-sys" }]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
version = 2
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
