name: Release notes

on:
  push:
    branches: [master]
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
